security:
    providers:
        web_service_user_provider:
          id:
            web_service_user_provider


    firewalls:
        secured_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: jwt_auth.jwt_authenticator
            provider: web_service_user_provider

    # Easy way to control access for large sections of your site
    access_control:
        - { path: ^/api/private, roles: ROLE_OAUTH_AUTHENTICATED }
        - { path: ^/api/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }