<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAeQTter\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAeQTter/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAeQTter.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAeQTter\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAeQTter\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AeQTter',
    'container.build_id' => '2844f188',
    'container.build_time' => 1565095887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAeQTter');
