<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jwt_auth.auth0_service' shared service.

include_once $this->targetDirs[3].'/vendor/auth0/jwt-auth-bundle/src/Security/Auth0Service.php';

return $this->privates['jwt_auth.auth0_service'] = new \Auth0\JWTAuthBundle\Security\Auth0Service('', 'dev-vrs2ps4n.auth0.com', 'http://localhost:8001/api', 'https://dev-vrs2ps4n.auth0.com/', false, $this->parameters['jwt_auth.supported_algs'], NULL);
